services:
  app:
    image: showtimex:dev
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app       # Mount current directory inside container
      - /usr/src/app/node_modules  # Prevent overwriting node_modules inside container
    ports:
      - '3000:3000'
    networks:
      - internal-net

  postgres: 
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: showtimex   # create the db on first run
    volumes:
      - db-data:/var/lib/postgresql/data   # Persist db data to named volume
    ports:
      - '5432:5432'
    networks:
      - internal-net

volumes:
  db-data:

networks:
  internal-net:
    driver: bridge