services:
  app:
    image: showtimex:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app       # Mount current directory inside container
      - /usr/src/app/node_modules  # Prevent overwriting node_modules inside container
    ports:
      - '3000:3000'