services:
  app:
    image: node-express-ts-app:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app       # Mount current directory inside container
      - /usr/src/app/node_modules  # Prevent overwriting node_modules inside container
    ports:
      - '3000:3000'
    depends_on:
      kafka:
          condition: service_healthy
      mongo:
          condition: service_started
  mongo:
    image: mongo:8.0.12
    volumes:
      - mongo-data:/data/db   # Persist mongo data to named volume
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "test-cluster-id"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mongo-data: