name: showtimex-prod
services:
  app:
    image: showtimex:prod
    build:
      context: ../
      target: prod
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ../env/.env
    ports:
      - 3000:3000
