name: Continiuous Integration & Deployment
run-name: ${{ github.run_id }} - Showtimex CI&CD - 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-runner/action.yml
      - name: Run linter
        run: npm run lint
      - run: echo "✅ Linter is alright."

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-runner/action.yml
      - name: Run tests
        run: npm run test
      - run: echo "✅ Tests passed"

  deploy:
    runs-on: ubuntu-latest
    needs: [run-linter, run-tests]
    steps:
      - name: 'Initiating Deployment'
        run: echo "Deploying..."
